development:
 adapter: postgresql
 encoding: unicode
 database: playalytics_dev
 host: localhost
 pool: 5
 username: jamesnewman
 password: password

test:
 adapter: postgresql
 encoding: unicode
 database: playalytics_test
 host: localhost
 pool: 5
 username: jamesnewman
 password: password

production:
 adapter: postgresql
 encoding: unicode
 database: playalytics
 host: localhost
 pool: 5
 username: jamesnewman
 password: password